TARGETS = putchr mnzcalc mentz.dat
CC = gcc
CCPARAM = -O2
GHC = ghc
GHCPARAM = -O2 -threaded

.PHONY: all
all: $(TARGETS)

putchr: putchr.c
	$(CC) $(CCPARAM) -o $@ $^

mnzcalc: mnzcalc.hs
	$(GHC) $(GHCPARAM) -o $@ $^

mentz.dat.001: putchr mnzcalc
	./mnzcalc 1 > $@
mentz.dat.002: putchr mnzcalc
	./mnzcalc 2 > $@
mentz.dat.003: putchr mnzcalc
	./mnzcalc 3 > $@
mentz.dat.004: putchr mnzcalc
	./mnzcalc 4 > $@
mentz.dat.005: putchr mnzcalc
	./mnzcalc 5 > $@
mentz.dat.006: putchr mnzcalc
	./mnzcalc 6 > $@
mentz.dat.007: putchr mnzcalc
	./mnzcalc 7 > $@
mentz.dat.008: putchr mnzcalc
	./mnzcalc 8 > $@
mentz.dat.009: putchr mnzcalc
	./mnzcalc 9 > $@
mentz.dat.010: putchr mnzcalc
	./mnzcalc 10 > $@
mentz.dat.011: putchr mnzcalc
	./mnzcalc 11 > $@
mentz.dat.012: putchr mnzcalc
	./mnzcalc 12 > $@
mentz.dat.013: putchr mnzcalc
	./mnzcalc 13 > $@
mentz.dat.014: putchr mnzcalc
	./mnzcalc 14 > $@
mentz.dat.015: putchr mnzcalc
	./mnzcalc 15 > $@
mentz.dat.016: putchr mnzcalc
	./mnzcalc 16 > $@
mentz.dat.017: putchr mnzcalc
	./mnzcalc 17 > $@
mentz.dat.018: putchr mnzcalc
	./mnzcalc 18 > $@
mentz.dat.019: putchr mnzcalc
	./mnzcalc 19 > $@
mentz.dat.020: putchr mnzcalc
	./mnzcalc 20 > $@
mentz.dat.021: putchr mnzcalc
	./mnzcalc 21 > $@
mentz.dat.022: putchr mnzcalc
	./mnzcalc 22 > $@
mentz.dat.023: putchr mnzcalc
	./mnzcalc 23 > $@
mentz.dat.024: putchr mnzcalc
	./mnzcalc 24 > $@
mentz.dat.025: putchr mnzcalc
	./mnzcalc 25 > $@
mentz.dat.026: putchr mnzcalc
	./mnzcalc 26 > $@
mentz.dat.027: putchr mnzcalc
	./mnzcalc 27 > $@
mentz.dat.028: putchr mnzcalc
	./mnzcalc 28 > $@
mentz.dat.029: putchr mnzcalc
	./mnzcalc 29 > $@
mentz.dat.030: putchr mnzcalc
	./mnzcalc 30 > $@
mentz.dat.031: putchr mnzcalc
	./mnzcalc 31 > $@
mentz.dat.032: putchr mnzcalc
	./mnzcalc 32 > $@
mentz.dat.033: putchr mnzcalc
	./mnzcalc 33 > $@
mentz.dat.034: putchr mnzcalc
	./mnzcalc 34 > $@
mentz.dat.035: putchr mnzcalc
	./mnzcalc 35 > $@
mentz.dat.036: putchr mnzcalc
	./mnzcalc 36 > $@
mentz.dat.037: putchr mnzcalc
	./mnzcalc 37 > $@
mentz.dat.038: putchr mnzcalc
	./mnzcalc 38 > $@
mentz.dat.039: putchr mnzcalc
	./mnzcalc 39 > $@
mentz.dat.040: putchr mnzcalc
	./mnzcalc 40 > $@
mentz.dat.041: putchr mnzcalc
	./mnzcalc 41 > $@
mentz.dat.042: putchr mnzcalc
	./mnzcalc 42 > $@
mentz.dat.043: putchr mnzcalc
	./mnzcalc 43 > $@
mentz.dat.044: putchr mnzcalc
	./mnzcalc 44 > $@
mentz.dat.045: putchr mnzcalc
	./mnzcalc 45 > $@
mentz.dat.046: putchr mnzcalc
	./mnzcalc 46 > $@
mentz.dat.047: putchr mnzcalc
	./mnzcalc 47 > $@
mentz.dat.048: putchr mnzcalc
	./mnzcalc 48 > $@
mentz.dat.049: putchr mnzcalc
	./mnzcalc 49 > $@
mentz.dat.050: putchr mnzcalc
	./mnzcalc 50 > $@
mentz.dat.051: putchr mnzcalc
	./mnzcalc 51 > $@
mentz.dat.052: putchr mnzcalc
	./mnzcalc 52 > $@
mentz.dat.053: putchr mnzcalc
	./mnzcalc 53 > $@
mentz.dat.054: putchr mnzcalc
	./mnzcalc 54 > $@
mentz.dat.055: putchr mnzcalc
	./mnzcalc 55 > $@
mentz.dat.056: putchr mnzcalc
	./mnzcalc 56 > $@
mentz.dat.057: putchr mnzcalc
	./mnzcalc 57 > $@
mentz.dat.058: putchr mnzcalc
	./mnzcalc 58 > $@
mentz.dat.059: putchr mnzcalc
	./mnzcalc 59 > $@
mentz.dat.060: putchr mnzcalc
	./mnzcalc 60 > $@
mentz.dat.061: putchr mnzcalc
	./mnzcalc 61 > $@
mentz.dat.062: putchr mnzcalc
	./mnzcalc 62 > $@
mentz.dat.063: putchr mnzcalc
	./mnzcalc 63 > $@
mentz.dat.064: putchr mnzcalc
	./mnzcalc 64 > $@
mentz.dat.065: putchr mnzcalc
	./mnzcalc 65 > $@
mentz.dat.066: putchr mnzcalc
	./mnzcalc 66 > $@
mentz.dat.067: putchr mnzcalc
	./mnzcalc 67 > $@
mentz.dat.068: putchr mnzcalc
	./mnzcalc 68 > $@
mentz.dat.069: putchr mnzcalc
	./mnzcalc 69 > $@
mentz.dat.070: putchr mnzcalc
	./mnzcalc 70 > $@
mentz.dat.071: putchr mnzcalc
	./mnzcalc 71 > $@
mentz.dat.072: putchr mnzcalc
	./mnzcalc 72 > $@
mentz.dat.073: putchr mnzcalc
	./mnzcalc 73 > $@
mentz.dat.074: putchr mnzcalc
	./mnzcalc 74 > $@
mentz.dat.075: putchr mnzcalc
	./mnzcalc 75 > $@
mentz.dat.076: putchr mnzcalc
	./mnzcalc 76 > $@
mentz.dat.077: putchr mnzcalc
	./mnzcalc 77 > $@
mentz.dat.078: putchr mnzcalc
	./mnzcalc 78 > $@
mentz.dat.079: putchr mnzcalc
	./mnzcalc 79 > $@
mentz.dat.080: putchr mnzcalc
	./mnzcalc 80 > $@
mentz.dat.081: putchr mnzcalc
	./mnzcalc 81 > $@
mentz.dat.082: putchr mnzcalc
	./mnzcalc 82 > $@
mentz.dat.083: putchr mnzcalc
	./mnzcalc 83 > $@
mentz.dat.084: putchr mnzcalc
	./mnzcalc 84 > $@
mentz.dat.085: putchr mnzcalc
	./mnzcalc 85 > $@
mentz.dat.086: putchr mnzcalc
	./mnzcalc 86 > $@
mentz.dat.087: putchr mnzcalc
	./mnzcalc 87 > $@
mentz.dat.088: putchr mnzcalc
	./mnzcalc 88 > $@
mentz.dat.089: putchr mnzcalc
	./mnzcalc 89 > $@
mentz.dat.090: putchr mnzcalc
	./mnzcalc 90 > $@
mentz.dat.091: putchr mnzcalc
	./mnzcalc 91 > $@
mentz.dat.092: putchr mnzcalc
	./mnzcalc 92 > $@
mentz.dat.093: putchr mnzcalc
	./mnzcalc 93 > $@
mentz.dat.094: putchr mnzcalc
	./mnzcalc 94 > $@
mentz.dat.095: putchr mnzcalc
	./mnzcalc 95 > $@
mentz.dat.096: putchr mnzcalc
	./mnzcalc 96 > $@
mentz.dat.097: putchr mnzcalc
	./mnzcalc 97 > $@
mentz.dat.098: putchr mnzcalc
	./mnzcalc 98 > $@
mentz.dat.099: putchr mnzcalc
	./mnzcalc 99 > $@
mentz.dat.100: putchr mnzcalc
	./mnzcalc 100 > $@
mentz.dat.101: putchr mnzcalc
	./mnzcalc 101 > $@
mentz.dat.102: putchr mnzcalc
	./mnzcalc 102 > $@
mentz.dat.103: putchr mnzcalc
	./mnzcalc 103 > $@
mentz.dat.104: putchr mnzcalc
	./mnzcalc 104 > $@
mentz.dat.105: putchr mnzcalc
	./mnzcalc 105 > $@
mentz.dat.106: putchr mnzcalc
	./mnzcalc 106 > $@
mentz.dat.107: putchr mnzcalc
	./mnzcalc 107 > $@
mentz.dat.108: putchr mnzcalc
	./mnzcalc 108 > $@
mentz.dat.109: putchr mnzcalc
	./mnzcalc 109 > $@
mentz.dat.110: putchr mnzcalc
	./mnzcalc 110 > $@
mentz.dat.111: putchr mnzcalc
	./mnzcalc 111 > $@
mentz.dat.112: putchr mnzcalc
	./mnzcalc 112 > $@
mentz.dat.113: putchr mnzcalc
	./mnzcalc 113 > $@
mentz.dat.114: putchr mnzcalc
	./mnzcalc 114 > $@
mentz.dat.115: putchr mnzcalc
	./mnzcalc 115 > $@
mentz.dat.116: putchr mnzcalc
	./mnzcalc 116 > $@
mentz.dat.117: putchr mnzcalc
	./mnzcalc 117 > $@
mentz.dat.118: putchr mnzcalc
	./mnzcalc 118 > $@
mentz.dat.119: putchr mnzcalc
	./mnzcalc 119 > $@
mentz.dat.120: putchr mnzcalc
	./mnzcalc 120 > $@
mentz.dat.121: putchr mnzcalc
	./mnzcalc 121 > $@
mentz.dat.122: putchr mnzcalc
	./mnzcalc 122 > $@
mentz.dat.123: putchr mnzcalc
	./mnzcalc 123 > $@
mentz.dat.124: putchr mnzcalc
	./mnzcalc 124 > $@
mentz.dat.125: putchr mnzcalc
	./mnzcalc 125 > $@

mentz.dat: \
mentz.dat.001 mentz.dat.002 mentz.dat.003 mentz.dat.004 mentz.dat.005 \
mentz.dat.006 mentz.dat.007 mentz.dat.008 mentz.dat.009 mentz.dat.010 \
mentz.dat.011 mentz.dat.012 mentz.dat.013 mentz.dat.014 mentz.dat.015 \
mentz.dat.016 mentz.dat.017 mentz.dat.018 mentz.dat.019 mentz.dat.020 \
mentz.dat.021 mentz.dat.022 mentz.dat.023 mentz.dat.024 mentz.dat.025 \
mentz.dat.026 mentz.dat.027 mentz.dat.028 mentz.dat.029 mentz.dat.030 \
mentz.dat.031 mentz.dat.032 mentz.dat.033 mentz.dat.034 mentz.dat.035 \
mentz.dat.036 mentz.dat.037 mentz.dat.038 mentz.dat.039 mentz.dat.040 \
mentz.dat.041 mentz.dat.042 mentz.dat.043 mentz.dat.044 mentz.dat.045 \
mentz.dat.046 mentz.dat.047 mentz.dat.048 mentz.dat.049 mentz.dat.050 \
mentz.dat.051 mentz.dat.052 mentz.dat.053 mentz.dat.054 mentz.dat.055 \
mentz.dat.056 mentz.dat.057 mentz.dat.058 mentz.dat.059 mentz.dat.060 \
mentz.dat.061 mentz.dat.062 mentz.dat.063 mentz.dat.064 mentz.dat.065 \
mentz.dat.066 mentz.dat.067 mentz.dat.068 mentz.dat.069 mentz.dat.070 \
mentz.dat.071 mentz.dat.072 mentz.dat.073 mentz.dat.074 mentz.dat.075 \
mentz.dat.076 mentz.dat.077 mentz.dat.078 mentz.dat.079 mentz.dat.080 \
mentz.dat.081 mentz.dat.082 mentz.dat.083 mentz.dat.084 mentz.dat.085 \
mentz.dat.086 mentz.dat.087 mentz.dat.088 mentz.dat.089 mentz.dat.090 \
mentz.dat.091 mentz.dat.092 mentz.dat.093 mentz.dat.094 mentz.dat.095 \
mentz.dat.096 mentz.dat.097 mentz.dat.098 mentz.dat.099 mentz.dat.100 \
mentz.dat.101 mentz.dat.102 mentz.dat.103 mentz.dat.104 mentz.dat.105 \
mentz.dat.106 mentz.dat.107 mentz.dat.108 mentz.dat.109 mentz.dat.110 \
mentz.dat.111 mentz.dat.112 mentz.dat.113 mentz.dat.114 mentz.dat.115 \
mentz.dat.116 mentz.dat.117 mentz.dat.118 mentz.dat.119 mentz.dat.120 \
mentz.dat.121 mentz.dat.122 mentz.dat.123 mentz.dat.124 mentz.dat.125
	cat $^ > $@

.PHONY: clean
clean:
	-rm *.hi *.o $(TARGETS) mentz.dat.*
