#pragma once

#define RULESIZE 760
#define RULES_IN_PAGE 40
#define RULE_IN_LINE 80
#define RULE_LINES ((RULESIZE+RULE_IN_LINE-1)/RULE_IN_LINE)
#define RULE_PAGES (RULESIZE/RULES_IN_PAGE)

#define NUM_OF_RULES RULESIZE

#define PREFERENCE_ITEMS 40
#define PREFERENCE_LINES ((PREFERENCE_ITEMS+RULE_IN_LINE-1)/RULE_IN_LINE)
#define PREFERENCE_PAGES (PREFERENCE_ITEMS/RULES_IN_PAGE)
