#pragma once

#define MIHAJONG_MAJOR_VER 1
#define MIHAJONG_MINOR_VER 99
#define MIHAJONG_PATCH_VER 3
#define MIHAJONG_VER "2.0beta3"

#define MJCORE_MAJOR_VER 1
#define MJCORE_MINOR_VER 99
#define MJCORE_PATCH_VER 3
#define MJCORE_VER "2.0beta3"

#define LOGGER_MAJOR_VER 2
#define LOGGER_MINOR_VER 0
#define LOGGER_PATCH_VER 0
#define LOGGER_VER "2.0.0"

#define ASTRO_MAJOR_VER 1
#define ASTRO_MINOR_VER 7
#define ASTRO_PATCH_VER 10
#define ASTRO_VER "1.7.10"

#define SOCKET_MAJOR_VER 1
#define SOCKET_MINOR_VER 99
#define SOCKET_PATCH_VER 1
#define SOCKET_VER "2.0beta1"

#define SOUND_MAJOR_VER 1
#define SOUND_MINOR_VER 99
#define SOUND_PATCH_VER 1
#define SOUND_VER "2.0beta1"

#define GRAPHIC_MAJOR_VER 1
#define GRAPHIC_MINOR_VER 99
#define GRAPHIC_PATCH_VER 3
#define GRAPHIC_VER "2.0beta3"
