#ifndef VERSION_H
#define VERSION_H

#define MIHAJONG_MAJOR_VER 1
#define MIHAJONG_MINOR_VER 7
#define MIHAJONG_PATCH_VER 2
#define MIHAJONG_VER "1.7.2"

#define MJCORE_MAJOR_VER 1
#define MJCORE_MINOR_VER 7
#define MJCORE_PATCH_VER 2
#define MJCORE_VER "1.7.2"

#define LOGGER_MAJOR_VER 1
#define LOGGER_MINOR_VER 6
#define LOGGER_PATCH_VER 0
#define LOGGER_VER "1.6.0"

#define ASTRO_MAJOR_VER 1
#define ASTRO_MINOR_VER 7
#define ASTRO_PATCH_VER 0
#define ASTRO_VER "1.7.0"

#define SOCKET_MAJOR_VER 1
#define SOCKET_MINOR_VER 8
#define SOCKET_PATCH_VER 0
#define SOCKET_VER "1.8.0"

#endif
